### ISSUE TITLE
Archive does not exist error

### ISSUE THREAD

**Issue by nobicycle** [nikosdion/facebook-auth#12]
#### Steps to reproduce the issue
<Joomla URL>/administrator/index.php?option=com_installer&view=install
Choose facebook-auth-master.zip

#### Expected result
Plugin installed

#### Actual result
Archive does not exist

See attachment
![0692189c-bbfb-4489-be9a-33b3d42ffbc8](https://cloud.githubusercontent.com/assets/1372447/23160557/ed7ac3c8-f861-11e6-96f3-0aac05b2628d.png)

#### System information (as much as possible)
Attached
![d341354d-bc9e-47a5-83e3-c80ead7592b0](https://cloud.githubusercontent.com/assets/1372447/23160598/0ff7b820-f862-11e6-91de-b1036bca9cf4.png)

**Comment by nikosdion** [comment]
I have rescinded the code required for this plugin from Joomla. Therefore this plugin is quite dead. In the future I might work on a custom component and module to support Facebook / Google+ / Twitter etc login.
